spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  docker:
    compose:
      enabled: true
      file: src/main/docker/docker-compose.yml
  flyway:

  thymeleaf:
    cache: false
