CREATE TABLE articles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp timestamp with time zone,
    author    varchar NOT NULL,
    titel     varchar NOT NULL,
    content   text    NOT NULL
);

ALTER TABLE articles
    ADD COLUMN ts tsvector
        GENERATED ALWAYS AS (to_tsvector('german', titel || ' ' || content || '' || author)) STORED;

CREATE INDEX articles_ts_idx ON articles USING GIN (ts);

